# Generated by Django 5.2.4 on 2025-08-27 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_rename_date_dailyreport_data_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailyreport',
            old_name='data',
            new_name='date',
        ),
    ]
