# Generated by Django 5.2.4 on 2025-08-28 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_rename_data_dailyreport_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyreport',
            name='profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
